import * as React from 'react';
import { View, StyleProp, ViewStyle } from 'react-native';

type Props = {
  width?: number;
  height?: number;
  style?: StyleProp<ViewStyle>;
};

// Placeholder used by multiple autogenerated screens that import from "../assets/"
const Placeholder = ({ width, height, style }: Props) => (
  <View style={[{ width: width ?? 24, height: height ?? 24 }, style]} />
);

export default Placeholder;
